### ISSUE TITLE
powergrid for visualizing pulse sequences

### ISSUE THREAD

**Issue by jayich** [Jayich-Lab/jax#18]

**Comment by fanmingyu212** [comment]
[DAX.sim](https://gitlab.com/duke-artiq/dax/-/wikis/DAX.sim/Overview) is likely the best way to do it, or at least a way we should look into. We should do some trials on a test setup to check possible side effects and incompatibilities.

Outputting to a VCD file is likely a good idea - gtkwave is a pretty good visualizer for the file that enables showing/hiding channels and zoom-in/out.
