### ISSUE TITLE
moves experiment explorer and scheduler from artiq to jax

### ISSUE THREAD

**Issue by fanmingyu212** [Jayich-Lab/jax#48]
We want to have more control on the experiment explorer and scheduler, including these capabilities:
* gets the experiment parameters when the experiment is scheduled to run, instead of when the experiment prepares to run: https://github.com/Jayich-Lab/pydux/issues/1870
* connects the explorer with the parameter bank applet to only show related parameters when an experiment is selected: https://github.com/Jayich-Lab/pydux/issues/1865
* adds progress bar on the scheduler: https://github.com/Jayich-Lab/pydux/issues/1920
* adds timestamps for messages in the log applet: https://github.com/Jayich-Lab/pydux/issues/1940

We also want to clean up the experiment explorer GUI, to remove functionalities such as experiment arguments (replaced by the parameter bank).

These changes require us moving away from using the explorer and scheduler GUI provided by artiq directly. We need to copy the related code to pydux and make modifications.

**Comment by mczimmermann** [comment]
I can also start working on this if we want, since I've been working a lot with the GUIs? It looks like we could use most of https://github.com/m-labs/artiq/tree/master/artiq/frontend

**Comment by mczimmermann** [comment]
Great! Should I wait for your PR to be approved first? Did you already implement a new/specialized artiq dashboard for our lab?

**Comment by fanmingyu212** [comment]
Probably good to wait for my PR. The PR will probably include a specialized artiq dashboard for our lab.
