### ISSUE TITLE
PMT differential mode notification when AOM is off

### ISSUE THREAD

**Issue by royaready** [Jayich-Lab/jax#81]
When the repump AOM is off and the user selects differential mode, nothing happens. This is because the AOM may have been turned off intentionally, e.g. if someone is doing work on that laser. or in that optical path.

When the AOM is off and the differential mode is selected, there should be some explicit notification that differential mode is not active. Print statements don't work in kernel mode. I chatted with Haoran and he floated the idea of writing some function in the server code that achieves this.

              If the repump AOM is off, the user mode should not be able to change to differential mode.

_Originally posted by @royaready in https://github.com/Jayich-Lab/jax/pull/80#discussion_r1162221948_

**Comment by fanmingyu212** [comment]
`rpc` with async to print can be used here.
